# functions in python

In [3]:
# void func_name(int a){}
def func_name(a,b):
  print(a,b)
  return a
x=func_name(1,2)
print(x)

1 2
1


# importing numpy package

In [4]:
import numpy as np

In [7]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


# n dimenstional

In [10]:
x1=np.array([1,2,34,76])#1D array
print(x1.ndim)
x1.shape

1


(4,)

In [12]:
x2=np.array([[1,2,34,76],[2,10,324,45]])#2D array
x2

array([[  1,   2,  34,  76],
       [  2,  10, 324,  45]])

In [13]:
x2.shape

(2, 4)

In [14]:
x2.size

8

In [15]:
x2.dtype

dtype('int64')

In [16]:
x2.itemsize

8

In [17]:
x2.nbytes

64

In [19]:
x2=x2.reshape(4,2)
x2

array([[  1,   2],
       [ 34,  76],
       [  2,  10],
       [324,  45]])

In [20]:
x2.flatten()

array([  1,   2,  34,  76,   2,  10, 324,  45])

In [23]:
a=np.arange(1,10,1)
b=np.array(np.random.rand(10)).reshape(5,2)
b

array([[0.76696457, 0.9879707 ],
       [0.95307631, 0.65152585],
       [0.52003624, 0.15666326],
       [0.86109043, 0.3601093 ],
       [0.83644936, 0.42486277]])

# indexing and slicing

In [25]:
arr=np.array(np.random.rand(25)).reshape(5,5)
arr

array([[0.77676508, 0.12683171, 0.62466002, 0.63356366, 0.36199669],
       [0.07093446, 0.75468032, 0.09963163, 0.73456075, 0.27060161],
       [0.21501471, 0.39803418, 0.45446547, 0.47929776, 0.89235259],
       [0.95067034, 0.53331111, 0.252489  , 0.21460311, 0.5244338 ],
       [0.73297722, 0.62599856, 0.98462683, 0.1922198 , 0.44033741]])

In [26]:
arr[0,0]#first element

0.7767650817557513

In [27]:
arr[0,:]

array([0.77676508, 0.12683171, 0.62466002, 0.63356366, 0.36199669])

In [28]:
arr[:,0]

array([0.77676508, 0.07093446, 0.21501471, 0.95067034, 0.73297722])

In [29]:
arr[:,:3]

array([[0.77676508, 0.12683171, 0.62466002],
       [0.07093446, 0.75468032, 0.09963163],
       [0.21501471, 0.39803418, 0.45446547],
       [0.95067034, 0.53331111, 0.252489  ],
       [0.73297722, 0.62599856, 0.98462683]])

In [30]:
arr[:3,:]

array([[0.77676508, 0.12683171, 0.62466002, 0.63356366, 0.36199669],
       [0.07093446, 0.75468032, 0.09963163, 0.73456075, 0.27060161],
       [0.21501471, 0.39803418, 0.45446547, 0.47929776, 0.89235259]])

In [33]:
arr[:2,1:3]

array([[0.12683171, 0.62466002],
       [0.75468032, 0.09963163]])

In [34]:
arr[1:4,1:4]

array([[0.75468032, 0.09963163, 0.73456075],
       [0.39803418, 0.45446547, 0.47929776],
       [0.53331111, 0.252489  , 0.21460311]])

In [36]:
arr[4,1:]

array([0.62599856, 0.98462683, 0.1922198 , 0.44033741])

In [37]:
for i in range(5):
  print(arr[i,i])

0.7767650817557513
0.7546803205958892
0.45446546608913085
0.21460311008276522
0.4403374145976373


# pandas

In [38]:
import pandas as pd

In [98]:

x=pd.read_csv("data1.csv")
x

math-1  math-2   phy  chem   sank  grade
0     65.0    58.0  49.0  38.0   88.0    8.4
1     74.0    71.0  58.0  58.0   98.0   10.0
2     65.0    66.0  35.0  45.0   77.0    8.0
3     66.0    69.0  45.0  55.0   95.0    9.4
4     45.0    48.0  55.0  49.0   99.0    8.4
5      0.0     0.0   0.0   0.0    0.0    0.0
6     35.0    29.0  26.0  37.0   55.0    5.6
7     22.0    20.0   9.0   8.0   45.0    3.0
8     30.0    45.0  25.0  35.0   75.0    5.8
9     75.0    25.0  54.0  15.0   67.0    6.6
10    74.0    73.0  12.0  17.0   43.0    6.0
11    25.0    67.0  20.0  60.0  100.0    7.4
12    34.0    23.0  60.0  45.0   73.0    6.8
13    75.0    75.0  60.0  60.0   99.0   10.0
14    74.0     2.0  59.0   2.0   50.0    5.4

In [99]:
x=pd.read_csv("data1.csv",index_col='math-1')#changing 1st column as index
x

math-2   phy  chem   sank  grade
math-1                                  
65.0      58.0  49.0  38.0   88.0    8.4
74.0      71.0  58.0  58.0   98.0   10.0
65.0      66.0  35.0  45.0   77.0    8.0
66.0      69.0  45.0  55.0   95.0    9.4
45.0      48.0  55.0  49.0   99.0    8.4
0.0        0.0   0.0   0.0    0.0    0.0
35.0      29.0  26.0  37.0   55.0    5.6
22.0      20.0   9.0   8.0   45.0    3.0
30.0      45.0  25.0  35.0   75.0    5.8
75.0      25.0  54.0  15.0   67.0    6.6
74.0      73.0  12.0  17.0   43.0    6.0
25.0      67.0  20.0  60.0  100.0    7.4
34.0      23.0  60.0  45.0   73.0    6.8
75.0      75.0  60.0  60.0   99.0   10.0
74.0       2.0  59.0   2.0   50.0    5.4

In [44]:
x['math-1']#by iloc we need not to worry columns 

0     65.0
1     74.0
2     65.0
3     66.0
4     45.0
5      0.0
6     35.0
7     22.0
8     30.0
9     75.0
10    74.0
11    25.0
12    34.0
13    75.0
14    74.0
Name: math-1, dtype: float64

In [45]:
x.iloc[:2,:3]

math-1  math-2   phy
0    65.0    58.0  49.0
1    74.0    71.0  58.0