In [19]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

In [20]:
data=pd.read_csv("data1.csv")
data  #Nan

math-1  math-2   phy  chem   sank  grade
0     65.0    58.0  49.0  38.0   88.0    8.4
1     74.0    71.0  58.0  58.0   98.0   10.0
2     65.0    66.0  35.0  45.0   77.0    8.0
3     66.0    69.0  45.0  55.0   95.0    9.4
4     45.0    48.0  55.0  49.0   99.0    8.4
5      0.0     0.0   0.0   0.0    0.0    0.0
6     35.0    29.0  26.0  37.0   55.0    5.6
7     22.0    20.0   9.0   8.0   45.0    3.0
8     30.0    45.0  25.0  35.0   75.0    5.8
9     75.0    25.0  54.0  15.0   67.0    6.6
10    74.0    73.0  12.0  17.0   43.0    6.0
11    25.0    67.0  20.0  60.0  100.0    7.4
12    34.0    23.0  60.0  45.0   73.0    6.8
13    75.0    75.0  60.0  60.0   99.0   10.0
14    74.0     2.0  59.0   2.0   50.0    5.4

In [21]:
x=data.iloc[:,:-1] #independent
y=data.iloc[:,-1]  #dependent

In [22]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y) #training data set and testing data set

In [23]:
lin=LinearRegression()
lin.fit(xtrain,ytrain)

LinearRegression()

In [24]:
res=lin.predict(xtest)
res

array([8.09963391, 0.43964161, 8.15123647, 5.82789741])

In [25]:
ytest

2    8.0
5    0.0
4    8.4
8    5.8
Name: grade, dtype: float64

In [27]:
res=res.astype(int)
ytest=ytest.astype(int)

In [28]:
confusion_matrix(ytest,res)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [29]:
res

array([8, 0, 8, 5])

In [30]:
ytest

2    8
5    0
4    8
8    5
Name: grade, dtype: int64