# pandas : Series and Data Frame

In [6]:
import pandas as pd
import numpy as np

In [5]:
x=pd.Series([{'a':1},{'b':2},{'c':3}],index=['x','y','z'])
x

x    {'a': 1}
y    {'b': 2}
z    {'c': 3}
dtype: object

In [12]:
#we cannot pass pandas in numpy
x1=pd.Series(np.array([1,2,3]))#pd.Series(np.array())
x2=pd.Series(np.array([4,5,6]))
x3=pd.Series(np.array([7,8,9]))
a=pd.DataFrame([{'a':x1,'b':x2,'c':x3}])
a

a                                  b  \
0  0    1
1    2
2    3
dtype: int64  0    4
1    5
2    6
dtype: int64   

                                   c  
0  0    7
1    8
2    9
dtype: int64

# Fancy indexing

In [13]:
x=np.array(np.random.rand(10)).reshape(5,2)
x

array([[0.87879903, 0.63753099],
       [0.68471429, 0.34211515],
       [0.39932155, 0.69096749],
       [0.19593668, 0.24445752],
       [0.96937105, 0.38428188]])

In [14]:
x[0]

array([0.87879903, 0.63753099])

In [15]:
x[x>0.5]

array([0.87879903, 0.63753099, 0.68471429, 0.69096749, 0.96937105])

In [16]:
x[x<0.1]

array([], dtype=float64)

In [17]:
x[x>1]

array([], dtype=float64)

In [18]:
x[0,1]

0.6375309911219921

# difference loc,iloc indexing

In [22]:
df=pd.DataFrame({'a':1,'b':2,'c':3},index=[0,1,2,3])
df

a  b  c
0  1  2  3
1  1  2  3
2  1  2  3
3  1  2  3

In [24]:
df['a']

0    1
1    1
2    1
3    1
Name: a, dtype: int64

In [25]:
df.iloc[0]

a    1
b    2
c    3
Name: 0, dtype: int64

In [26]:
data=pd.read_excel('std_details_s.xlsx')#(r'c:\name')
data

course_name course_id  attempted_id   cand_name       cand_email  marks  \
0        chem     A6025            90  20881A0562  dskjc@kjdsnc.cd    100   
1          ml     A5720           456  20881A0593     dsjb@jdkfn.c     99   
2     physics     A5645          4556  20881A05B1          fsv@d.j      0   
3          ml     A5720           234  20881A05B1          fsv@d.j     50   
4        chem     A6025            65  20881A05B1          fsv@d.j     34   
5     physics     A5645          4556  20881A0562  dskjc@kjdsnc.cd     45   
6     physics     A5645            23  20881A05B5     ekjwf@kjn.cd     67   
7          ml     A5720           456  20881A05C1    jkvs@fdkv.dsf     23   
8          ml     A5720           435  20881A0545         dfg@f.ef     94   
9        chem     A6025           435  20881A05B2        gfsd@ds.d     75   

  grade     status  
0    A+  very good  
1     A  very good  
2     F  very poor  
3     B    average  
4     C       poor  
5     B    average  
6    B+       good  
7     F  very poor  
8    A+  very good  
9     A       good

In [27]:
data.head()

course_name course_id  attempted_id   cand_name       cand_email  marks  \
0        chem     A6025            90  20881A0562  dskjc@kjdsnc.cd    100   
1          ml     A5720           456  20881A0593     dsjb@jdkfn.c     99   
2     physics     A5645          4556  20881A05B1          fsv@d.j      0   
3          ml     A5720           234  20881A05B1          fsv@d.j     50   
4        chem     A6025            65  20881A05B1          fsv@d.j     34   

  grade     status  
0    A+  very good  
1     A  very good  
2     F  very poor  
3     B    average  
4     C       poor

In [28]:
data['course_name'].replace('chem','math')

0       math
1         ml
2    physics
3         ml
4       math
5    physics
6    physics
7         ml
8         ml
9       math
Name: course_name, dtype: object

In [30]:
data['course_name'].replace('chem','1')

0          1
1         ml
2    physics
3         ml
4          1
5    physics
6    physics
7         ml
8         ml
9          1
Name: course_name, dtype: object

In [31]:
data['course_name'].dtype

dtype('O')

In [32]:
data['attempted_id'].astype(float)

0      90.0
1     456.0
2    4556.0
3     234.0
4      65.0
5    4556.0
6      23.0
7     456.0
8     435.0
9     435.0
Name: attempted_id, dtype: float64

In [35]:
data=data.drop('course_id',axis=1)

In [36]:
data

course_name  attempted_id   cand_name       cand_email  marks grade  \
0        chem            90  20881A0562  dskjc@kjdsnc.cd    100    A+   
1          ml           456  20881A0593     dsjb@jdkfn.c     99     A   
2     physics          4556  20881A05B1          fsv@d.j      0     F   
3          ml           234  20881A05B1          fsv@d.j     50     B   
4        chem            65  20881A05B1          fsv@d.j     34     C   
5     physics          4556  20881A0562  dskjc@kjdsnc.cd     45     B   
6     physics            23  20881A05B5     ekjwf@kjn.cd     67    B+   
7          ml           456  20881A05C1    jkvs@fdkv.dsf     23     F   
8          ml           435  20881A0545         dfg@f.ef     94    A+   
9        chem           435  20881A05B2        gfsd@ds.d     75     A   

      status  
0  very good  
1  very good  
2  very poor  
3    average  
4       poor  
5    average  
6       good  
7  very poor  
8  very good  
9       good